CC = gcc
CFLAGS = -O3 -Wall -lpthread

clean:
	rm -rf *.o MyRAMBench

run: 
	 sbatch RWR_1000_1t.slurm
	 sbatch RWR_1000_2t.slurm
	 sbatch RWR_1000_4t.slurm
	 sbatch RWR_10000_1t.slurm
	 sbatch RWR_10000_2t.slurm
	 sbatch RWR_10000_4t.slurm
	 sbatch RWR_100000_1t.slurm
	 sbatch RWR_100000_2t.slurm 	
	 sbatch RWR_100000_4t.slurm
	 sbatch RWR_1_1t.slurm
	 sbatch RWR_1_2t.slurm
	 sbatch RWR_1_4t.slur
	 sbatch RWS_1000_1t.slurm
	 sbatch RWS_1000_2t.slurm
	 sbatch RWS_1000_4t.slurm
	 sbatch RWS_10000_1t.slurm
	 sbatch RWS_10000_2t.slurm
	 sbatch RWS_10000_4t.slurm
	 sbatch RWS_100000_1t.slurm
	 sbatch RWS_100000_2t.slurm
	 sbatch RWS_100000_4t.slurm
	 sbatch RWS_1000000_1t.slurm
	 sbatch RWS_1000000_2t.slurm
	 sbatch RWS_1000000_4t.slurm
	 sbatch RWS_1_1t.slurm
	 sbatch RWS_1_2t.slurm
	 sbatch RWS_1_4t.slurm
