CC=gcc
CFLAGS=-g -Wall -O2 -pthread

runTCP_1_1:
	sbatch TCP_1_1t_server.slurm
	sbatch TCP_1_1t_client.slurm

runTCP12:
	sbatch TCP12s.slurm
	sbatch TCP12c.slurm

runTCP14:
	sbatch TCP14s.slurm
	sbatch TCP14c.slurm

runTCP18:
	sbatch TCP18s.slurm
	sbatch TCP18c.slurm

runTCP10001:
	sbatch TCP10001s.slurm
	sbatch TCP10001c.slurm

runTCP10002:
	sbatch TCP10002s.slurm
	sbatch TCP10002c.slurm

runTCP10004:
	sbatch TCP10004s.slurm
	sbatch TCP10004c.slurm

runTCP10008:
	sbatch TCP10008s.slurm
	sbatch TCP10008c.slurm

runTCP320001:
	sbatch TCP320001s.slurm
	sbatch TCP320001c.slurm

runTCP320002:
	sbatch TCP320002s.slurm
	sbatch TCP320002c.slurm

runTCP320004:
	sbatch TCP320004s.slurm
	sbatch TCP320004c.slurm

runTCP320008:
	sbatch TCP320008s.slurm
	sbatch TCP320008c.slurm





